spring:
  h2:
    console:
      enabled: true
      path: /egobooster
  thymeleaf:
    cache: false
  redis:
    host: egobooster-redis.z3suka.0001.usw1.cache.amazonaws.com
    port: 6379

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://egobooster-database.c50mcel7fyxh.us-west-1.rds.amazonaws.com:3306/egobooster
    username: admin
    password: Egobooster1!

  jpa:
    database: mysql
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true