spring:
  h2:
    console:
      enabled: true
      path: /egobooster
  thymeleaf:
    cache: false
  redis:
    host: localhost
    port: 6379

  #  datasource:
  #    driver-class-name: org.h2.Driver
  #    url: jdbc:h2:file:./egobooster;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;
  #    username: egobooster
  #    password:
  #
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/egobooster
    username: root
    password: Egobooster1!

  jpa:
    database: mysql
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
#    show-sql: true
#    database-platform: org.hibernate.dialect.H2Dialect
#    properties:
#      hibernate:
#        format_sql: true
#    hibernate:
#      ddl-auto: update
#    open-in-view: false
